# Generated by Django 4.2.2 on 2023-06-19 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_alter_student_hobbies_alter_teacher_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='document',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='document',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
